version: '2.4'

services:
  rabbitmq:
    image: rabbitmq:3
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 5s
      timeout: 5s
      retries: 3
    ports:
        - "5672:5672"
